<?xml version="1.0" ?>
<testCase duration="0.171" fail="1" name="SET-251" pass="0" startdate="20160216" starttime="124325">
	<block fail="0" pass="0"/>
	<block fail="0" pass="0"/>
	<block fail="1" pass="0">
		<block fail="1" pass="0">
			<call fail="1" pass="0">functions.raiseError('Intentional exception in execution phase')</call>
			<call fail="0" pass="0">functions.raiseError('Should not run')</call>
		</block>
		<block fail="1" pass="0">
			<call fail="1" pass="0">functions.raiseError('Should not run')</call>
		</block>
	</block>
	<block fail="1" pass="0">
		<call fail="1" pass="0">functions.raiseError('Should not run')</call>
	</block>
</testCase>
